### ISSUE TITLE
Subsets - give all subsets containing exactly n elements. 

### ISSUE THREAD

**Issue by axkr** [dpaukov/combinatoricslib3#12]
Is there an implementation for subsets containing exactly `n` elements.?

This can of course be done with the `stream()` API, but I assume it will be faster, if its already implemented in the subset iterator itself.

In case you provide an implementation, the ordering of subsets should also be adjusted.

Instead of this ordering in your example:

```
   []
   [one]
   [two]
   [one, two]
   [three]
   [one, three]
   [two, three]
   [one, two, three]
```

It should be ordered like this IMO:

```
   []
   [one]
   [two]
   [three]
   [one, two]
   [one, three]
   [two, three]
   [one, two, three]
```

**Comment by dpaukov** [comment]
If you need all subsets containing exactly `n` elements, you can use the simple combination generator `Generator.combination(array).simple(n)`. The similar approach can be used for generating all subsets in ascending order of their size (number of elements):

```
static <T> void exactSizeSubSet(T[] arr, int n) {
      assert(n >= 0);
      assert(n <= arr.length);
      Generator.combination(arr)
             .simple(n)
             .stream()
             .forEach(System.out::println);
}

static <T> void allOrderedSubSets(T[] arr) {
     IntStream.rangeClosed(0, arr.length)
         .forEach(i -> Generator.combination(arr)
             .simple(i)
             .stream()
             .forEach(System.out::println));
}
```

**Comment by dpaukov** [comment]
I assume I can close this issue.
