### ISSUE TITLE
Add a cartesian product with collection input parameter.

### ISSUE THREAD

**Issue by FlorianCousin** [dpaukov/combinatoricslib3#13]
Varargs is very convenient when we want to write each parameter at function call.
However, it is quite less convenient when the input parameters we have are in a `List` because converting `List<List<AnyType>>` into `List<AnyType>[]` is not easy in Java.
I think it would be useful to have a cartesian product with in collection input parameter like it is already done for `subset`, `permutation` and `combination`.

**Comment by FlorianCousin** [comment]
I am sorry but I am a bit unaware of the habits on GitHub open source projects.
Can I open a PR for this ? Or do I need a validation of the issue from the repository owner ?

**Comment by dpaukov** [comment]
The change is available in version 3.3.1.
