### ISSUE TITLE
Apache 2.0 compatible license option?

### ISSUE THREAD

**Issue by raedma** [dpaukov/combinatoricslib3#23]
Hi,

thanks for the great library. I was thinking about using it in a (future) open source project of mine. However, the complete list of dependencies in my code uses some kind of Apache 2.0 compatible license, so I would like to use Apache 2.0 as well. However, this seems to prevent me from using `combinatoricslib3` as it is under LGPLv3 and from my understanding using `combinatoricslib3` in a new project would require my project to be under LGPL as well. Is there any chance you would think about dual-licensing the library to be compatible with ASF libraries, e.g. LGPLv3 + Apache 2.0?

Regards
Martin

**Comment by dpaukov** [comment]
Version 3.4.0 has been released under Apache License 2.0: https://github.com/dpaukov/combinatoricslib3/wiki/v3.4.0
