### ISSUE TITLE
Is version 3.1.0 ready ?

### ISSUE THREAD

**Issue by idreamshen** [dpaukov/combinatoricslib3#3]
Thx

**Comment by dpaukov** [comment]
No, it is not ready yet. I expect it to be ready for releasing by the end of this month (aug 2016). 
Meanwhile you can configure your project to use a [snapshot version of the library](https://oss.sonatype.org/content/repositories/snapshots/com/github/dpaukov/combinatoricslib3/3.1.0-SNAPSHOT) or use [combinatoricslib 2.1](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.googlecode.combinatoricslib%22%20AND%20a%3A%22combinatoricslib%22)
```
<snapshotRepository>
    <id>ossrh</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
</snapshotRepository>
```

```
<dependency>
    <groupId>com.github.dpaukov</groupId>
    <artifactId>combinatoricslib3</artifactId>
    <version>3.1.0-SNAPSHOT</version>
</dependency>
```

**Comment by idreamshen** [comment]
ok
