### ISSUE TITLE
Combinations of lists?

### ISSUE THREAD

**Issue by KevinTyrrell** [dpaukov/combinatoricslib3#4]
I have n lists all of the same type. I want to loop through all the possible combinations of pulling one item from each of those lists. 

Ex.

List 1 = { Red, Blue, Orange }
List 2 = { Brown }
List 3 = { White, Black }

Red Brown White
Red Brown Black
Blue Brown White
Blue Brown Black
Orange Brown White
Orange Brown Black

How can I do that with this library? Thanks

**Comment by dpaukov** [comment]
This enhancement (cartesian product generator) will be released by the end of May 2018 in version 3.2.1

**Comment by dpaukov** [comment]
https://github.com/dpaukov/combinatoricslib3#7-cartesian-product

**Comment by KevinTyrrell** [comment]
Great addition. Thanks.
